### ISSUE TITLE
Is it possible to get better labels on the pictures?

### ISSUE THREAD

**Issue by dwormuth** [hdiessner/Allskycam-heating#1]
I'd like to build your design but I'm finding the plugs on the relay to be confusing. My version has the left-sided bent pins labeled  S + - top to bottom with the printing right side up and the right-sided relay screws are unlabelled. 

The cables appear to be overlapped and I cannot tell if there are any junctions. Possible to provide a clearer diagram?

Thanks,
Dave

**Comment by hdiessner** [comment]
Thank you Dave, I added 2 schematics images with details on the wiring. Hope this helps.
