### ISSUE TITLE
 Problem using the program integration into smart home environment using MQTT

### ISSUE THREAD

**Issue by flipper07** [hdiessner/Allskycam-heating#3]
Hello I just installed the system on my raspberry.
But I don't understand how to make it work.
Are you talking about mqtt commands but I don't know.

Could you explain to me how to do, I don't know MQTT and how to install it
Thank you very much for helping me.
Sorry for the translation I'm french

**Comment by hdiessner** [comment]
duplicate to https://github.com/hdiessner/Allskycam-heating/issues/2
